const assert = require("assert");
const { matchesFacets, setCardVisibility } = require("../assets/features.js");
assert.strictEqual(matchesFacets(["ring", "volva"], new Set()), true);
assert.strictEqual(matchesFacets(["ring", "volva"], new Set(["ring"])), true);
assert.strictEqual(matchesFacets(["ring", "volva"], new Set(["ring", "volva"])), true);
assert.strictEqual(matchesFacets(["ring"], new Set(["ring", "volva"])), false);
assert.strictEqual(matchesFacets([], new Set(["ring"])), false);
const card = { style: { display: "initial" } };
setCardVisibility(card, true);
assert.strictEqual(card.style.display, "");
setCardVisibility(card, false);
assert.strictEqual(card.style.display, "none");
console.log("feature filter tests passed");
